services:
  forum:
    build:
      context: ./forum
      dockerfile: Dockerfile
    container_name: forum
    expose:
      - "3001"
    environment:
      - SECRET_KEY_BASE=SECRET_KEY_BASE=b43f30a3175bafd6babf571b06f5d4ed2b79245b7300fe993619012853d85d29a382b76fca24703d7722acae08ec75517edc29d2991a87f2aa51f04e9ae154c5
    restart: unless-stopped
    networks:
      - ionos

networks:
  ionos:
    external: true